### ISSUE TITLE
Consider legacy n-makefile issues

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/n-gage#54]
- [ ]  [gitignore pa11y_screenCapture](https://github.com/Financial-Times/n-makefile/issues/170)
- [ ]  [n-ui test for components fails when n-ui is only used in 1 of either bower or package.json](https://github.com/Financial-Times/n-makefile/issues/162)
- [ ]  [.gitignore hack](https://github.com/Financial-Times/n-makefile/issues/98)
- [ ]  [Handle typos](https://github.com/Financial-Times/n-makefile/issues/37)
- [ ]  [Better error messages when CLI tools missing](https://github.com/Financial-Times/n-makefile/issues/19)
- [x]  [lintspaces is run on binary files](https://github.com/Financial-Times/n-makefile/issues/111)
- [x]  [.slugignore](https://github.com/Financial-Times/n-makefile/issues/83)
- [x]  [If releases API call fails, installation command silently echoes "Not Found" into n.Makefile](https://github.com/Financial-Times/n-makefile/issues/66)
- [x]  [Patches & autoupdates](https://github.com/Financial-Times/n-makefile/issues/29)
- [x]  [How to 'whitesource' from Makefile](https://github.com/Financial-Times/n-makefile/issues/23)
- [x]  [Experiment with pulling n-makefile in via a git submodule](https://github.com/Financial-Times/n-makefile/issues/22)
- [x]  [Testing solution](https://github.com/Financial-Times/n-makefile/issues/8)
